language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: wrnz7VAz2Kn7KzBpfkMf4o6uDjG/jwHSVgQ9zdoOQN6cjhzrXmq7lW7UxtpYpwd5Dejy61XAacFjVdih7DTXDvdjB7r3mpBFwhL1rncfPaP3N1PCP2pFyX4Rse2KKhg7Y8pc1rkjadOS+HJ15k2wVLtUPxz3t2q0MOT48YKFMg4=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: 5L5R78KMbAt72Lqj90r9MxCSOMKn7T8dTrrxJvPBL6yWV9QYvcXiAoxbv5f/+SN9ci1FEgsuD74QRgZXC98+Wy9qygeAClkYAJp8rZj30/P1zQNkUwxTjSWcn/MV6Mu0PBB5pRPYx2+d+JVUZmInEe4EpUuaLn1VNCjBChwGYVI=
sudo: false
