language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: PoJqsNM+QwGWCqzr7r4cAxEC8uNjQL5ucTlv+gIaKhvpcQE8nsVZxH04Epkx91rO4wAUQT51MpNFM5SVkcA44PELTU3QeHXEKu4g0s5QtKJmrftZM3KrhZ/Q12pkKJXZBQHL10QxHljVJpNe9lp3CCkjGGafbZTnuvFSq0j7oX4=
notifications:
  email: false
  slack:
    secure: 5L5R78KMbAt72Lqj90r9MxCSOMKn7T8dTrrxJvPBL6yWV9QYvcXiAoxbv5f/+SN9ci1FEgsuD74QRgZXC98+Wy9qygeAClkYAJp8rZj30/P1zQNkUwxTjSWcn/MV6Mu0PBB5pRPYx2+d+JVUZmInEe4EpUuaLn1VNCjBChwGYVI=
sudo: false
